### ISSUE TITLE
Import to anki (sentences) working incorrectly.

### ISSUE THREAD

**Issue by Geniusssmit** [Garethp/RikaiRebuilt#5]
Import to anki (sentences) working incorrectly.
Instead of sentence importing kind of definition of the next word with some weird stuff.
![screenshot_3](https://user-images.githubusercontent.com/24941285/46610544-ba95d980-cb13-11e8-900b-38f6e41c3238.png)
![screenshot_4](https://user-images.githubusercontent.com/24941285/46610545-bb2e7000-cb13-11e8-9df0-9fcdfe882d0c.png)

**Comment by Garethp** [comment]
Sorry for the delay. I should have it fixed in `1.1.6`, which is out now. Give it a try and let me know

**Comment by Geniusssmit** [comment]
Now works well!!
One more problem: there is import frequency information in anki but not in pop up.

**Comment by Garethp** [comment]
Have you enabled frequency information in `Settings -> Dictionaries`?
